export const settings = {
    screenSize: 1,
    playSound: true,
    vibrate: true,
    displayShell: true,
    displayShellButtons: true,
    displayShellLogo: true,
    shellShape: 6,
    backgroundColor: '#FFDEAD',
    backgroundPattern: 'resources/img/ui/bg_pattern_01.png',
    notifications: false,
    automaticAging: true,
    sleepingHoursOffset: 0,
    classicMainMenuUI: false,
    isTester: false,
    theme: false,
    shellAdditionalSize: 0,
    showWantName: true,
    genderedPets: false,
    playMusic: true,
    skillsAffectingEvolution: true,
    season: 'auto',
}