import "/resources/data/SpriteDefinitions.js"
import "/resources/data/CharacterDefinitions.js"
import "/resources/data/SoundDefinitions.js"
import "/resources/data/GrowthChart.js"

// import "./libs/profanity-cleaner-0.0.3.js"
// import "./libs/moment.js"
// import "./libs/idb-keyval.js"

import "./Utils.js"
import "./Version.js"
import "./UiHelper.js"
import "./Drawer.js"
import "./Object2d.js"
import "./Scene.js"
import "./Activities.js"
import "./PetDefinition.js"
import "./Pet.js"
import "./Animal.js"
import "./Plant.js"
import "./App.js"
import "./Definitions.js"
import "./Missions.js"
import "./StoryGen.js"
import "./Main.js"