name: itch-deploy-main

# Trigger on push to gh-pages branch
on:
  workflow_dispatch: 
  push:
    branches:
      - gh-pages

jobs:
  deploy-to-itch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Create filtered ZIP archive
        run: |
          zip -r itch-upload.zip . \
            -x "*.git*" \
            -x "*README.md" \
            -x "*scripts/*" \
            -x "*.vscode/*" \
            -x "*.blog/*" \
            -x "*.creator/*" \
            -x "*.growth-chart/*" \
            -x "*.DS_Store"
  
      - name: Setup butler
        uses: remarkablegames/setup-butler@v3

      - name: Upload to Itch.io via Butler
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_BUTLER_API_KEY }}
        run: |
          butler push itch-upload.zip samandev/tamaweb-staging:html5 --userversion ${{ github.run_number }}
